---
title: "Hw07_map"
author: "Hy Mak"
date: "5/14/2018"
output: html_document
---

```{r setup}
library(tidyverse)
library(knitr)
library(broom)
library(stringr)
library(modelr)
library(forcats)
library(ggmap)
library(rgdal)
library(maps)
library(maptools)
library(readr)
library(tidyr)
library(maptools)
if (!require(gpclib)) install.packages("gpclib", type="source")
gpclibPermit()
library(ggthemes)
library(gganimate)
library(animation)

options(digits = 3)
set.seed(1234)
theme_set(theme_minimal())

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE
)
```


```{r}
library(raster)
world <- readShapeSpatial( "TM_WORLD_BORDERS-0/TM_WORLD_BORDERS-0.3.shp")

# http://www.r-graph-gallery.com/169-170-basic-manipulation-of-shapefiles/
# Keep only Africa
Africa <- world[world@data$REGION==2 , ]
plot(Africa , xlim=c(-20,60) , ylim=c(-40,35) )

fortify(Africa) %>%
  head()

as_tibble(Africa@data)

Africa2 <- Africa %>%
fortify(region = "ISO3") %>%
  as_tibble() %>%
  left_join(Africa@data, by = c("id" = "ISO3"))

as.tibble(Africa2)
```

```{r}
africa_WB <- read_csv("~/Desktop/cfss/hw07/africa_WB.csv")

africa_WB_clean <- africa_WB %>%
  rename(Rule_of_Law = "Rule of Law: Percentile Rank [RL.PER.RNK]",
           Anti_Corruption = "Control of Corruption: Percentile Rank [CC.PER.RNK]",
           Gov_Effectiveness = "Government Effectiveness: Percentile Rank [GE.PER.RNK]",
           Pol_Stability = "Political Stability and Absence of Violence/Terrorism: Percentile Rank [PV.PER.RNK]",
           Regulatory = "Regulatory Quality: Percentile Rank [RQ.PER.RNK]",
           Year = "Time",
           country = "Country Code") %>%
#Select 
  dplyr::select(Year, 
           country, 
           Rule_of_Law, 
           Anti_Corruption,
           Pol_Stability) %>%
#Change Year to numeric   
  mutate(Year = as.numeric(Year), 
         law_cut = cut_interval(as.numeric(Rule_of_Law), 5),
         stability_cut  = cut_interval(as.numeric(Pol_Stability), 5),
         corruption_cut = cut_interval(as.numeric(Anti_Corruption), 5))

africa_WB_clean
```





```{r}
africa_WB_clean %>%
ggplot(aes(map_id = country)) +
  geom_map(aes(fill = law_cut), map = Africa2) +
  expand_limits(x = Africa2$long, y = Africa2$lat) +
  ggthemes::theme_map() +
  labs(title = "Rule of Law in Africa",
        fill = NULL) +
  scale_fill_brewer(palette = "Reds", na.value = "gray") +
  coord_fixed(1.3) +
  theme_void()
```

```{r}
africa_WB_clean %>%
ggplot(aes(map_id = country)) +
  geom_map(aes(fill = corruption_cut), map = Africa2) +
  expand_limits(x = Africa2$long, y = Africa2$lat) +
  ggthemes::theme_map() +
  labs(title = "Control of Corruption in Africa",
        fill = NULL) +
  scale_fill_brewer(palette = "Blues", na.value = "gray") +
  coord_fixed(1.3) +
  theme_void()
```

```{r}
africa_WB_clean %>%
ggplot(aes(map_id = country)) +
  geom_map(aes(fill = stability_cut), map = Africa2) +
  expand_limits(x = Africa2$long, y = Africa2$lat) +
  ggthemes::theme_map() +
  labs(title = "Political Stability in Africa",
        fill = NULL) +
  scale_fill_brewer(palette = "Paired", na.value = "gray") +
  coord_fixed(1.3) +
  theme_void()
```

```{r}
p <- ggplot(africa_WB_clean, aes(map_id = country, frame = Year)) +
  geom_map(aes(fill = law_cut), map = Africa2) +
  expand_limits(x = Africa2$long, y = Africa2$lat) +
  labs(title = "Rule of Law in Africa",
        fill = NULL) +
  scale_fill_brewer(palette = "Blues", na.value = "gray") +
  ggthemes::theme_map() +
  theme(legend.position = "none")

gganimate(p)

```

```{r}

```